version: '3.8'

services:
  frontend:
    image: gordito908/frontend-app:latest
    ports:
      - "8080:80"
    depends_on:
      - api-gateway

  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USERS_SERVICE_URL=http://auth-service:3001
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=database
      - DB_USER=dev-admin
      - DB_PASSWORD=dev-123
      - DB_NAME=medimicro_db
      - DB_PORT=5432
    depends_on:
      - database

database:
    image: postgres:15-alpine
    container_name: medimicro-db
    environment:
      POSTGRES_USER: dev-admin
      POSTGRES_PASSWORD: dev-123
      POSTGRES_DB: medimicro_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./auth-service/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: